export const cloudData = [
  { text: "Blockchain", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Artificial Intelligence", value: Math.floor(Math.random() * 9) + 1 },
  { text: "AWS Cloud", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Internet of Things", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Physics", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Cybersecurity", value: Math.floor(Math.random() * 9) + 1 },
  { text: "India", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Machine Learning", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Web Development", value: Math.floor(Math.random() * 9) + 1 },
  { text: "TypeScript", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Next.js", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Biology", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Robotics", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Drones", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Geography", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Aerospace", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Quantum Computing", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Nanotechnology", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Smart Cities", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Renewable Energy", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Cryptocurrency", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Metaverse", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Augmented Reality", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Chemistry", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Autonomous Vehicles", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Fintech", value: Math.floor(Math.random() * 9) + 1 },
  { text: "World Politics", value: Math.floor(Math.random() * 9) + 1 },
  { text: "3D Printing", value: Math.floor(Math.random() * 9) + 1 },
  { text: "SpaceX", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Tesla", value: Math.floor(Math.random() * 9) + 1 },
  { text: "Mars", value: Math.floor(Math.random() * 9) + 1 },
];
