name: Ping Cron Job

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Hit the ping endpoint
        run: |
          curl --request GET \
          --url '${{ secrets.BASE_URL }}/api/ping' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
